# Generated by Django 5.2.17 on 2026-10-01 05:41

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=core.ids.book_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('publication_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('access_type', models.CharField(choices=[('open_access', 'Open access'), ('subscription', 'Subscription'), ('free_preview', 'Free preview')], default='subscription', max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.CharField(default=core.ids.case_study_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('publication_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('access_type', models.CharField(choices=[('open_access', 'Open access'), ('subscription', 'Subscription'), ('free_preview', 'Free preview')], default='subscription', max_length=20)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('instructor_resources_available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'case studies',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.CharField(default=core.ids.journal_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('access_type', models.CharField(choices=[('open_access', 'Open access'), ('subscription', 'Subscription'), ('free_preview', 'Free preview')], default='subscription', max_length=20)),
                ('latest_volume', models.CharField(blank=True, max_length=60)),
                ('established', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='catalog.book')),
            ],
            options={
                'ordering': ['book_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=core.ids.article_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list, help_text='List of author display names.')),
                ('summary', models.TextField(help_text='Abstract.')),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('publication_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('access_type', models.CharField(choices=[('open_access', 'Open access'), ('subscription', 'Subscription'), ('free_preview', 'Free preview')], default='subscription', max_length=20)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('citation_count', models.PositiveIntegerField(default=0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('full_text_available', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='catalog.journal')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
