# Generated by Django 5.2.17 on 2026-10-01 05:41

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=core.ids.submission_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('article', 'Journal article'), ('book_proposal', 'Book proposal'), ('case_study', 'Case study')], default='article', max_length=20)),
                ('author_names', models.CharField(blank=True, help_text='Comma separated author list as typed in the form.', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('revision_requested', 'Revision requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('published', 'Published')], db_index=True, default='submitted', max_length=20)),
                ('last_decision', models.CharField(blank=True, choices=[('desk_reject', 'Desk reject'), ('revise', 'Request revision'), ('accept', 'Accept'), ('reject', 'Reject'), ('withdraw', 'Withdraw'), ('publish', 'Publish')], max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='catalog.journal')),
                ('published_article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='catalog.article')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('desk_reject', 'Desk reject'), ('revise', 'Request revision'), ('accept', 'Accept'), ('reject', 'Reject'), ('withdraw', 'Withdraw'), ('publish', 'Publish')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workflow.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.CharField(default=core.ids.review_id, max_length=40, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('submitted', 'Submitted')], default='invited', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='workflow.submission')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
    ]
